"""
reports/report_gen.py
Generates HTML, JSON, or TXT pentest reports from ScanResult.
"""
import json, time
from pathlib import Path
from typing import Union
from utils.logger import get_logger
logger = get_logger("report_gen")

SEVERITY_COLOR = {"CRITICAL":"#e74c3c","HIGH":"#e67e22","MEDIUM":"#f1c40f","LOW":"#27ae60","INFO":"#3498db"}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NetPhantom Report — {target}</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:'Courier New',monospace;background:#0a0e17;color:#c9d1d9;line-height:1.6;padding:2rem}}
  h1{{color:#58a6ff;font-size:1.8rem;margin-bottom:.3rem}}
  h2{{color:#79c0ff;font-size:1.1rem;margin:2rem 0 .8rem;border-bottom:1px solid #21262d;padding-bottom:.4rem}}
  .meta{{color:#8b949e;font-size:.85rem;margin-bottom:2rem}}
  .risk{{display:inline-block;padding:.2rem .7rem;border-radius:3px;font-weight:bold;font-size:.8rem}}
  table{{width:100%;border-collapse:collapse;font-size:.88rem;margin-bottom:1.5rem}}
  th{{background:#161b22;color:#8b949e;text-align:left;padding:.5rem .8rem;border:1px solid #21262d}}
  td{{padding:.5rem .8rem;border:1px solid #21262d;vertical-align:top}}
  tr:nth-child(even){{background:#0d1117}}
  .sev{{font-weight:bold;padding:.1rem .5rem;border-radius:3px;font-size:.8rem}}
  .CRITICAL{{background:#7d0000;color:#ffaaaa}}
  .HIGH{{background:#7d3a00;color:#ffd08a}}
  .MEDIUM{{background:#6b5900;color:#ffe87a}}
  .LOW{{background:#0d4a1e;color:#7fff9e}}
  .INFO{{background:#003366;color:#7fc0ff}}
  .score-bar{{background:#161b22;border-radius:4px;height:12px;width:200px;display:inline-block;vertical-align:middle;margin-left:.5rem}}
  .score-fill{{background:linear-gradient(90deg,#238636,#e67e22,#e74c3c);height:100%;border-radius:4px}}
  .port-open{{color:#3fb950}}
  code{{background:#161b22;padding:.1rem .3rem;border-radius:3px;font-size:.85rem}}
  .section{{background:#0d1117;border:1px solid #21262d;border-radius:6px;padding:1.2rem;margin-bottom:1.5rem}}
  footer{{color:#8b949e;font-size:.75rem;margin-top:3rem;border-top:1px solid #21262d;padding-top:1rem}}
</style>
</head>
<body>
<h1>&#128272; NetPhantom Pentest Report</h1>
<div class="meta">
  Target: <strong>{target}</strong> &nbsp;|&nbsp;
  OS Guess: <strong>{os_guess}</strong> &nbsp;|&nbsp;
  Generated: <strong>{timestamp}</strong> &nbsp;|&nbsp;
  Duration: <strong>{duration}s</strong>
</div>

<div class="section">
<h2>&#9888; Risk Summary</h2>
<table>
<tr><th>Open Ports</th><th>Total Vulns</th><th>Critical</th><th>High</th><th>Risk Score</th></tr>
<tr>
  <td>{open_ports}</td>
  <td>{vuln_total}</td>
  <td><span class="sev CRITICAL">{critical}</span></td>
  <td><span class="sev HIGH">{high}</span></td>
  <td>{risk_score}/100
    <span class="score-bar"><span class="score-fill" style="width:{risk_score}%"></span></span>
  </td>
</tr>
</table>
</div>

<div class="section">
<h2>&#128270; Open Ports &amp; Services</h2>
<table>
<tr><th>Port</th><th>Service</th><th>Banner</th></tr>
{port_rows}
</table>
</div>

<div class="section">
<h2>&#128161; Vulnerabilities</h2>
{vuln_rows}
</div>

<div class="section">
<h2>&#128214; Reconnaissance</h2>
{recon_section}
</div>

<footer>Generated by NetPhantom &nbsp;|&nbsp; For authorized use only &nbsp;|&nbsp; {timestamp}</footer>
</body>
</html>"""


class ReportGenerator:
    def __init__(self, scan_result):
        self.r = scan_result if isinstance(scan_result, dict) else scan_result.to_dict()

    def generate(self, fmt: str = "html", path: str = "report.html") -> str:
        if fmt == "json":
            return self._write_json(path)
        elif fmt == "txt":
            return self._write_txt(path)
        return self._write_html(path)

    def _write_json(self, path: str) -> str:
        Path(path).write_text(json.dumps(self.r, indent=2, default=str))
        return path

    def _write_txt(self, path: str) -> str:
        lines = [
            f"NetPhantom Report — {self.r['target']}",
            "=" * 50,
            f"OS: {self.r.get('os_guess','?')}",
            "",
            "OPEN PORTS",
        ]
        for p in self.r.get("open_ports", []):
            lines.append(f"  {p['port']}/tcp  {p.get('service','')}  {p.get('banner','')[:60]}")
        lines.append("\nVULNERABILITIES")
        for v in self.r.get("vulnerabilities", []):
            lines.append(f"  [{v['severity']}] {v['cve']} (port {v['port']}): {v['description']}")
        Path(path).write_text("\n".join(lines))
        return path

    def _write_html(self, path: str) -> str:
        s = self.r.get("summary", {})

        port_rows = "".join(
            f"<tr><td class='port-open'>{p['port']}/tcp</td>"
            f"<td>{p.get('service','?')}</td>"
            f"<td><code>{(p.get('banner') or '')[:80]}</code></td></tr>"
            for p in self.r.get("open_ports", [])
        ) or "<tr><td colspan='3'>No open ports found</td></tr>"

        if self.r.get("vulnerabilities"):
            vuln_table = "<table><tr><th>CVE</th><th>Port</th><th>Severity</th><th>Description</th><th>Fix</th></tr>"
            for v in self.r["vulnerabilities"]:
                sev = v["severity"]
                vuln_table += (
                    f"<tr><td><code>{v['cve']}</code></td>"
                    f"<td>{v['port']}</td>"
                    f"<td><span class='sev {sev}'>{sev}</span></td>"
                    f"<td>{v['description']}</td>"
                    f"<td>{v['recommendation']}</td></tr>"
                )
            vuln_rows = vuln_table + "</table>"
        else:
            vuln_rows = "<p style='color:#3fb950'>No vulnerabilities detected.</p>"

        recon = self.r.get("recon_data", {})
        recon_html = ""
        if recon.get("whois"):
            recon_html += "<strong>WHOIS</strong><table>" + "".join(
                f"<tr><td style='color:#8b949e;width:160px'>{k}</td><td>{v}</td></tr>"
                for k, v in list(recon["whois"].items())[:8]
            ) + "</table><br>"
        if recon.get("dns"):
            recon_html += "<strong>DNS Records</strong><table>" + "".join(
                f"<tr><td style='color:#8b949e;width:80px'>{rtype}</td><td>{'<br>'.join(vals)}</td></tr>"
                for rtype, vals in recon["dns"].items()
            ) + "</table>"

        html = HTML_TEMPLATE.format(
            target=self.r["target"],
            os_guess=self.r.get("os_guess", "Unknown"),
            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
            duration=s.get("duration_seconds", "?"),
            open_ports=s.get("open_ports", len(self.r.get("open_ports", []))),
            vuln_total=s.get("vulnerabilities_total", len(self.r.get("vulnerabilities", []))),
            critical=s.get("critical", 0),
            high=s.get("high", 0),
            risk_score=s.get("risk_score", 0),
            port_rows=port_rows,
            vuln_rows=vuln_rows,
            recon_section=recon_html or "<p style='color:#8b949e'>No recon data.</p>",
        )
        Path(path).write_text(html)
        return path
